apiVersion: v1
kind: Service
metadata:
  name: echoserver-service
spec:
  type: NodePort
  selector:
    app: echoserver
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31337
